name: BWH Stock Monitor

on:
  schedule:
    # 每 5 小时（北京时间 0点、5点、10点、15点、20点）自动启动一次
    - cron: '0 */5 * * *'
  workflow_dispatch: 

jobs:
  check:
    runs-on: ubuntu-latest
    # 既然要长跑，把超时时间设为 360 分钟（6小时）
    timeout-minutes: 360
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Monitor
      env:
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
      run: python monitor.py
